name: seek_qr_camera
description: "Prueba tecnica para seek usando patrón BLoc e integración Nativa."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #State
  flutter_bloc: ^9.1.0 
  #Utils
  pinput: ^5.0.1
  equatable: ^2.0.7
  pigeon: ^24.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

