// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.camera.qr.seek.seek_qr_camera;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class BiometricAuthApi {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class AuthRequest {
    private @Nullable String promptMessage;

    public @Nullable String getPromptMessage() {
      return promptMessage;
    }

    public void setPromptMessage(@Nullable String setterArg) {
      this.promptMessage = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      AuthRequest that = (AuthRequest) o;
      return Objects.equals(promptMessage, that.promptMessage);
    }

    @Override
    public int hashCode() {
      return Objects.hash(promptMessage);
    }

    public static final class Builder {

      private @Nullable String promptMessage;

      @CanIgnoreReturnValue
      public @NonNull Builder setPromptMessage(@Nullable String setterArg) {
        this.promptMessage = setterArg;
        return this;
      }

      public @NonNull AuthRequest build() {
        AuthRequest pigeonReturn = new AuthRequest();
        pigeonReturn.setPromptMessage(promptMessage);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(1);
      toListResult.add(promptMessage);
      return toListResult;
    }

    static @NonNull AuthRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      AuthRequest pigeonResult = new AuthRequest();
      Object promptMessage = pigeonVar_list.get(0);
      pigeonResult.setPromptMessage((String) promptMessage);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class AuthResponse {
    private @Nullable Boolean success;

    public @Nullable Boolean getSuccess() {
      return success;
    }

    public void setSuccess(@Nullable Boolean setterArg) {
      this.success = setterArg;
    }

    private @Nullable String errorMessage;

    public @Nullable String getErrorMessage() {
      return errorMessage;
    }

    public void setErrorMessage(@Nullable String setterArg) {
      this.errorMessage = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      AuthResponse that = (AuthResponse) o;
      return Objects.equals(success, that.success) && Objects.equals(errorMessage, that.errorMessage);
    }

    @Override
    public int hashCode() {
      return Objects.hash(success, errorMessage);
    }

    public static final class Builder {

      private @Nullable Boolean success;

      @CanIgnoreReturnValue
      public @NonNull Builder setSuccess(@Nullable Boolean setterArg) {
        this.success = setterArg;
        return this;
      }

      private @Nullable String errorMessage;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorMessage(@Nullable String setterArg) {
        this.errorMessage = setterArg;
        return this;
      }

      public @NonNull AuthResponse build() {
        AuthResponse pigeonReturn = new AuthResponse();
        pigeonReturn.setSuccess(success);
        pigeonReturn.setErrorMessage(errorMessage);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(success);
      toListResult.add(errorMessage);
      return toListResult;
    }

    static @NonNull AuthResponse fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      AuthResponse pigeonResult = new AuthResponse();
      Object success = pigeonVar_list.get(0);
      pigeonResult.setSuccess((Boolean) success);
      Object errorMessage = pigeonVar_list.get(1);
      pigeonResult.setErrorMessage((String) errorMessage);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return AuthRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return AuthResponse.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof AuthRequest) {
        stream.write(129);
        writeValue(stream, ((AuthRequest) value).toList());
      } else if (value instanceof AuthResponse) {
        stream.write(130);
        writeValue(stream, ((AuthResponse) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface BiometricAuthApi {

    @NonNull 
    AuthResponse authenticate(@NonNull AuthRequest request);

    /** The codec used by BiometricAuthApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `BiometricAuthApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable BiometricAuthApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable BiometricAuthApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.seek_qr_camera.BiometricAuthApi.authenticate" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                AuthRequest requestArg = (AuthRequest) args.get(0);
                try {
                  AuthResponse output = api.authenticate(requestArg);
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
